- name: Install required Python packages
  pip:
    name:
      - kubernetes

- name: Activate conda and verify
  shell: |
    source /home/rajan/miniconda3/etc/profile.d/conda.sh
    conda activate network_security
    python3 -m pip show kubernetes
  args:
    executable: /bin/bash
