## we will refer to this to create artifacts directory
artifacts_root: artifacts

data_ingestion:
    ingestion_dir: artifacts/data_ingestion ## root directory
    collection_name: NetworkData
    database_name: PhishingData
    file_name: datafromDB.csv

data_validation:
    root_dir: artifacts/data_validation #root directoy for validation tasks
    ingestion_file: artifacts/data_ingestion/datafromDB.csv ## data ingestion file
    STATUS_FILE: artifacts/data_validation/status.txt ##status truE or false

data_transformation:
    root_dir: artifacts/data_transformation
    data_path: artifacts/data_ingestion/datafromDB.csv

model_trainer:
    root_dir: artifacts/model_trainer
    train_data_path: artifacts/data_transformation/train.csv
    test_data_path: artifacts/data_transformation/test.csv
    mlflow_uri: https://dagshub.com/rajan-31/E2E-Network-Security.mlflow
    mlflow_experiment: Model_Training_Experiment
    standard_scaler_name: ss.pkl

model_evaluation:
    root_dir: artifacts/model_evaluation
    test_data_path: artifacts/data_transformation/test.csv
    metric_file_name: artifacts/model_evaluation/metrics.json
    mlflow_uri: https://dagshub.com/rajan-31/E2E-Network-Security.mlflow
    ss_file_path: artifacts/model_trainer/ss.pkl