## we will refer to this to create artifacts directory
artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion ## root directory
    source_dir: NetworkSecurity/PriorETL/data.csv ##read from
    ingested_dir: artifacts/data_ingestion ## data ingestion
    collection_name: NetworkData
    database_name: PhishingData