- name: Install required Python packages
  pip:
    name:
      - kubernetes

- name: Activate python environment and verify
  shell: |
    source /home/rajan/0.Projects/SPE-final-project/backend/.e2e_nw_sec/bin/activate
    python3 -m pip show kubernetes
  args:
    executable: /bin/bash
