name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        working-directory: ./backend
        run: echo "Linting repository"

      - name: Run unit tests
        working-directory: ./backend
        run: echo "Running unit tests"

  build-and-push-dockerhub:
    name: Push to Docker Hub
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        working-directory: ./backend
        run: |
          DOCKERHUB_REPO=${{ secrets.DOCKERHUB_USERNAME }}/my-image
          IMAGE_TAG=latest
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
          docker push $DOCKERHUB_REPO:$IMAGE_TAG

  deploy-on-local:
    name: Run Ansible on Localhost
    needs: build-and-push-dockerhub
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Ansible
        working-directory: ./backend
        run: |
          # pip install -r requirements.txt

          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_password_file

          ansible-playbook -i ansible/inventory ansible/playbook.yaml --vault-password-file ~/.vault_password_file