# comment for trigger build x
name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        working-directory: ./backend
        run: echo "Linting repository"

      - name: Run basic backend tests
        working-directory: ./backend
        env:
          JWT_SECRET_KEY: "test_secret_key_for_github_actions"
          MONGO_DB_URL: "mongodb://localhost:27017"
          MLFLOW_TRACKING_URI: "http://localhost:5000"
        run: |
          pip install pytest pytest-cov fastapi httpx pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pytest tests/test_api.py::test_login_endpoint tests/test_api.py::test_signup_endpoint -v
      
      - name: Run frontend tests (placeholder)
        working-directory: ./frontend
        run: echo "Frontend tests will be added here"

  build-and-push-backend:
    name: Build and Push Backend Docker
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        working-directory: ./backend
        run: |
          DOCKERHUB_REPO=${{ secrets.DOCKERHUB_USERNAME }}/backend-image
          IMAGE_TAG=latest
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
          docker push $DOCKERHUB_REPO:$IMAGE_TAG
  
  build-and-push-frontend:
    name: Build and Push Frontend Docker
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push frontend image
        working-directory: ./frontend
        run: |
          FRONTEND_REPO=${{ secrets.DOCKERHUB_USERNAME }}/frontend-image
          IMAGE_TAG=latest
          docker build -t $FRONTEND_REPO:$IMAGE_TAG .
          docker push $FRONTEND_REPO:$IMAGE_TAG


  deploy-on-local:
    name: Run Ansible on Localhost
    needs: [ build-and-push-frontend,build-and-push-backend]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Ansible
        working-directory: ./ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_password_file

          ansible-playbook -i inventory playbook.yaml --vault-password-file ~/.vault_password_file